### ISSUE TITLE
test module: setup could not be imported

### ISSUE THREAD

**Issue by Wouter1** [INFLUENCEorg/aienvs#40]
When you run the junit tests (at least, from Eclipse) you get

```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/setup.py", line 44, in <module>
    data_files.append(('pydevd_attach_to_process', [os.path.join('pydevd_attach_to_process', f) for f in os.listdir('pydevd_attach_to_process') if accept_file(f)]))
FileNotFoundError: [Errno 2] No such file or directory: 'pydevd_attach_to_process'
ERROR: Module: setup could not be imported (file: /home/wouter/git/aienvs/setup.py).
```

**Comment by Wouter1** [comment]
There are similar reports for PyCharm (IntelliJ)
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000021859-PyCharm-Python-Console-fails-to-import-variables-in-setup-py

**Comment by Wouter1** [comment]
That leads to https://youtrack.jetbrains.com/issue/PY-30480 and https://youtrack.jetbrains.com/issue/PY-26654
