### ISSUE TITLE
connection default is already active

### ISSUE THREAD

**Issue by Wouter1** [INFLUENCEorg/aienvs#43]
Some students report issues with ports / connections when using SumoGymAdapter environment
(see attached stack trace from one of the students).
Please investigate whether SumoGymAdapter, when used i.e. within the Episode.py execution loop (e.g. with a random agent)
handles resources (like ports) correctly -- that is resources are released at the end of each episode,
and the port that was released can be used for connections again.
I suspect there may be a resource leak somewhere. 

```
Traceback (most recent call last):
File "8scproj-aiagents/aiagents/sing1e/300tstrappedDW'run_bootstrap.py", line 673, in <module>
File "BscProj-aiagents/aiagents/sing1e/300tstrappedDQN/run bootstrap.py", line 238, in train
File "/tudelft. net/staff-umbre11a/inf1uenceteam/BscProj-aienvs/aienvs/Sumo/SumoGymAdapter.py", line 125,
self. )
File "/tudelft. net/staff-umbre11a/inf1uenceteam/Bscproj-aienvs/aienvs/Sumo/Sum06ymAdapter.py", line 199,
self. ldm. start(sumoCmd, self ._port)
File "/tudelft. net/staff-umbre11a/inf1uenceteam/BscProj-aienvs/aienvs/Sumo/LW.py", line 67, in start
self. start (sumCmd, port=PORT)
File "/tudelft. net/staff-umbrella/influenceteam/sumo/tools/traci/main.py", line 124, in start
raise TraCIException("Connection 'Xs' is already active." X label)
raci.exceptions . TraCIException: Connection 'default' is already active.
srun: error: influl: task Exited with exit code 1
in reset
in star-tsun

```

**Comment by Wouter1** [comment]
Checking sumo source code
https://github.com/eclipse/sumo/blob/master/tools/traci/main.py

It seems this error occurs when the "default" connection already exists It would typically occur if sumo.start()  is called twice.

**Comment by Wouter1** [comment]
We need to test a number of things here
* Does Env specify that close should be called before creating a new env? Should it?
* Does SumoGymAdapter close and then create a new one work
* Does Episode call close? should it?

**Comment by Wouter1** [comment]
I can call env.close() after running a PPO loop in the test, but it works anyway, also if I don't call env.close(). 

So although we might expect that close needs to be called, it actually does nothing to explain or fix this issue

I first need to reproduce this

**Comment by Wouter1** [comment]
SUMO_client points to a traci from /sumo/tools/traci.py
```
def start(cmd, port=None, numRetries=10, label="default"):
    """
    Start a sumo server using cmd, establish a connection to it and
    store it under the given label. This method is not thread-safe.
    """
    if port is None:
        port = sumolib.miscutils.getFreeSocketPort()
    sumoProcess = subprocess.Popen(cmd + ["--remote-port", str(port)])
    _connections[label] = connect(port, numRetries, "localhost", sumoProcess)
    switch(label)
    return getVersion()

```

**Comment by Wouter1** [comment]
ldm.start is only called in _startSUMO. Can we somehow call _startSUMO multiple times throught he SumoGymAdapter?

_startSUMO is called from reset() and from __init__. 

But reset will always first call ldm.close() 

Maybe call __init__ multiple times? Eg create two SumoGymAdapters and not calling reset()? 

But even that just works I think because SumoGymAdapter _startSUMO picks a random port anyway even though parameters contains a port number

**Comment by Wouter1** [comment]
Even if I disable SumoGymAdapter random port picking and set port always to 10001, do not close and do not reset, it keeps working.

**Comment by Wouter1** [comment]
@czechows I tried to reproduce this by deliberately disabling the picking of random port numbers in SumoGymAdapter plus not closing or resetting the adapter after use.  But it keeps working anyway 

I have no clue on how to reproduce this, even if I want it and try to break the code.

We need more detailed info on how to reproduce this

**Comment by czechows** [comment]
@Wouter1 that is useful though strange that the resources are still somehow released automatically.. It is difficult to reproduce since the error appeared after many hours of running on INSY cluster.

So let's make a summary of what works:

1. Two parallel executions on same port 10001 -- probably not
2. Two parallel executions on random port choice -- probably yes (in _startSUMO we should go to the catch block and retry)?
3. One after another, same port, previously we have not called close/reset -- yes (surprisingly).
4. One after another, same port, let's say in previous simulation the program crashed (possibly resource leak?) -- could you please test this.
5. Also, in the except block can you add some debugging message and see whether it is executed often (@miguelsuau suspected that after many hours on the cluster this except is being called more often, which slows down the execution).

**Comment by Wouter1** [comment]
Checking the rest of Alex' question

>If that works fine, please check whether two separate instances of the program can run simultaneously and independently on the same machine and that they don't get stuck stealing each others ports.

**Comment by Wouter1** [comment]
To test this I run this
```
python -m unittest -v test.testSumoGymAdapter
```
in the aienvs directory, in two terminals simultaneously

**Comment by Wouter1** [comment]
If I leave in the self.port=10001 hack to force some problem, I do get an error in the 2nd user:
```
Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
Quitting (on error).
```

If I use the original code that picks random port numbers, both tests run and complete fine in parallel.

**Comment by Wouter1** [comment]
@czechows  I can run two testSumoGymAdapter junit tests in parallel, where both use the SumoGym adapter.

**Comment by Wouter1** [comment]
I am getting warnings now that I did not close sockets, which is to be expected since I removed the close() calls for testing. 

Weird is that this happens even after reboot:
```
(venv) wouter@tud206796:~/git/aienvs$ python -m unittest -v test.testSumoGymAdapter
test_new_traffic (test.testSumoGymAdapter.testSumoGymAdapter) ...  Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 34340)>
  time.sleep(wait)
/home/wouter/git/aienvs/venv/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
 Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 47012)>
  time.sleep(wait)
ok
test_runTwice (test.testSumoGymAdapter.testSumoGymAdapter) ...  Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 42484)>
  time.sleep(wait)
 Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 47268)>
  time.sleep(wait)
 Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 42966)>
  time.sleep(wait)
 Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 46314)>
  time.sleep(wait)
ok
test_smoke (test.testSumoGymAdapter.testSumoGymAdapter) ...  Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 36338)>
  time.sleep(wait)
 Retrying in 1 seconds
Loading configuration... done.
/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 39914)>
  time.sleep(wait)
ok

----------------------------------------------------------------------
Ran 3 tests in 10.045s

```

**Comment by Wouter1** [comment]
@czechows I can finally confirm some resource leak.
I get a warning on the console, but ONLY if I run the junit test from the terminal; not when I run from Eclipse...

What is also interesting is that the reported non-closed sockets are in the 30000-50000 range. The socket numbers that we pick ourselves are in the 10000-20000 range. So there seems something else going on here.

I can imagine that if you run long enough, then even the retry-scheme for random ports will fail when enough ports are already in use. This is  hard to test with the current way the code is written - we can't run for hours till all sockets are in use. It should be written more controllable to make this in a junit test. But it's not clear to me yet how to fix this to make this testable

**Comment by Wouter1** [comment]
This shows the open and not closing ports. They appear tcp portsfrom and to high port numbers, all in the 40000+ range
```netstat -ct```

**Comment by Wouter1** [comment]
The messages say
>/home/wouter/sumo/tools/traci/__init__.py:73: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 47012)>
> time.sleep(wait)


So the error message comes from a call inside traci ```time.sleep(wait)``` ??

maybe
https://emptysqua.re/blog/against-resourcewarnings-in-python-3/

**Comment by Wouter1** [comment]
here https://emptysqua.re/blog/against-resourcewarnings-in-python-3/ they argue that the "ResourceWarning" message is useless, as the socket closing is all automatically managed by python

OTOH I can see these sockets remaining open. So something in python is not 'garbage collecting' as expected.

**Comment by Wouter1** [comment]
Manually checking the netstat output, I can see that the ports in the 10k-20k range ARE indeed automatically closed and GC'ed

But those in the 40k-50k range stay open

**Comment by Wouter1** [comment]
EDIT. There are a few ports in 40k-50k range that remain open but this list does not increase over time.

There are other ports also in the 30k-50k range that is opened but also is closed automatically

**Comment by czechows** [comment]
Perhaps there is an "empty run" of SUMO being started somewhere else in the code by accident, which consumes the ports from the 40-50k range?

**Comment by Wouter1** [comment]
@czechows manually checking the netstat and reading https://emptysqua.re/blog/against-resourcewarnings-in-python-3/ it seems that sockets are closed automatically but after a timeout of a few minutes. In fact they claim that the resourcewarning is out of place.

Is it possible that in some server configurations the number of used ports gets large enough so that we can not find a free port within the number of available tries? 

So this problem happens inside traci, on a connect attempt with 10 retries, on a time.sleep call, on something that should be automatically GC'ed. 

It seems way out of our hands to be able to fix anything

**Comment by czechows** [comment]
> @czechows manually checking the netstat and reading https://emptysqua.re/blog/against-resourcewarnings-in-python-3/ it seems that sockets are closed automatically but after a timeout of a few minutes. In fact they claim that the resourcewarning is out of place.
> 
> Is it possible that in some server configurations the number of used ports gets large enough so that we can not find a free port within the number of available tries?

Yes, it could be. There are many parallel jobs running on the cluster for many hours.

> 
> So this problem happens inside traci, on a connect attempt with 10 retries, on a time.sleep call, on something that should be automatically GC'ed.
> 
> It seems way out of our hands to be able to fix anything

I understand. If this is inside traci, it is also not something we can fix via changes to our library. I guess by relying on GC they didn't suspect the execution abuse we do on the cluster. But we also can use an alternate backend (libsumo) that seems to be working for most cases and doesn't have these issues.

As last steps in this issue (for tomorrow, I guess), could you please:

1. Have a job run for few hours in the background (while working on other things), and check with netstat whether there are significantly more ports occupied than at the beginning.

2. Summarize the answers to questions 1-5 of my message in the last comment before closing. 

Thanks!

**Comment by Wouter1** [comment]
@czechows  which job do you want to run? I usually only run the junit tests and they last up to a minute, not hours.

**Comment by czechows** [comment]
@Wouter1 sorry I meant: adjust (or make a script out of) a unit test, extend the execution time significantly by increasing the number of steps or episodes.

**Comment by Wouter1** [comment]
1    Two parallel executions on same port 10001 -- probably not

The second one asking for port 10001 is refused

2.    Two parallel executions on random port choice -- probably yes (in _startSUMO we should go to the catch block and retry)?

Works all fine

3    One after another, same port, previously we have not called close/reset -- yes (surprisingly).

Works anyway. 

4.   One after another, same port, let's say in previous simulation the program crashed (possibly resource leak?) -- could you please test this.

I did try by not closing the port and restarting which just works. I'm not sure how you want to crash the program. I can maybe kill with ctrl-C but this is C so sockets will be closed by the OS anyway if python exits.

5.   Also, in the except block can you add some debugging message and see whether it is executed often (@miguelsuau suspected that after many hours on the cluster this except is being called more often, which slows down the execution).

Ok I added a logger.critical if the exception is not "connection closed by SUMO" in SumoGymAdapter. I suppose this is the one we need to log but I can't reproduce  this so it's untested

**Comment by Wouter1** [comment]
@czechows  thanks for the clarification.
I modify testSumoGymAdapter,#test_runTwice

Instead of calling              self._runPpoLoop() twice I do this
```
        for n in range(100000):
             self._runPpoLoop()
```

Each run is only 1000 steps and takes 0.5s. So the number of sockets to be GC'ed grows quite rapidly but seems to stabilize at around 50. I guess that's related to the GC delay time.

Every cycle is accompanied by exactly 1 ResourceWarning unclosed socket. Everything seems to run fine.

**Comment by Wouter1** [comment]
I let it run for about half an hour (no more time available today).
I did not see anything special happen.
